apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multi-k8s-corywtason-net-tls
spec:
  secretName: multi-k8s-corywtason-net
  issuerRef:
    letsencrypt-prod
  kind: ClusterIssuer
  commonName: mulit-k8s.corywatson.net
  dnsNames:
    - multi-k8s.corywatson.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mulit-k8s.corywatson.net