apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-corywtason-net-tls
spec:
  secretName: multi-k8s-corywtason-net
  issuerRef:
    name: letsencrypt-prod
  commonName: multi-k8s.corywatson.net
  dnsNames:
    - multi-k8s.corywatson.net